# Generated by Django 4.1 on 2022-08-23 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0003_despesas_valor_alter_vendas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='descricao_despesa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 22, 45, 1, 852860)),
        ),
    ]
